<a href="https://colab.research.google.com/github/dabhimanyu/learn_to_code/blob/python_codes/001_Mike_Python_lec_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = 3
b = 4
print(a)
b

3


4

In [2]:
%whos
%reset -f

Variable   Type    Data/Info
----------------------------
a          int     3
b          int     4


In [3]:
%whos

Interactive namespace is empty.


In [4]:
# Creating Lists:
# List -> []

aList = [0 , 1 , 2 , 3 , 4 , 5]
print(aList)
%whos

[0, 1, 2, 3, 4, 5]
Variable   Type    Data/Info
----------------------------
aList      list    n=6


In [5]:
strList = ['Hy' , 'my' , 'name' , 'is' , 'Abhimanyu']
strList
%whos

Variable   Type    Data/Info
----------------------------
aList      list    n=6
strList    list    n=5


In [6]:
mixList = [1 , '7' , 7 , 7.0]
print(mixList)

[1, '7', 7, 7.0]


In [7]:
listList = [1 , 2 , 3 , [5 , 6 , 7] , 8]
print(listList)
%whos

[1, 2, 3, [5, 6, 7], 8]
Variable   Type    Data/Info
----------------------------
aList      list    n=6
listList   list    n=5
mixList    list    n=4
strList    list    n=5


In [8]:
aList = [0 , 1 , 2 , 3 , 4 , 5 , 6]
%whos
5.1 not in aList

Variable   Type    Data/Info
----------------------------
aList      list    n=7
listList   list    n=5
mixList    list    n=4
strList    list    n=5


True

In [9]:
print(aList)
print(strList)
print(aList + strList )

[0, 1, 2, 3, 4, 5, 6]
['Hy', 'my', 'name', 'is', 'Abhimanyu']
[0, 1, 2, 3, 4, 5, 6, 'Hy', 'my', 'name', 'is', 'Abhimanyu']


In [10]:
# Methods:

# NOTE: Methods are specific to the type of objects:

print(aList)
aList.append(100)
print(aList)

[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 100]


In [11]:
aList.sort()
print(aList)

[0, 1, 2, 3, 4, 5, 6, 100]


In [12]:
# Tuples:
%reset -f
# A tuple is immutable, while a list is mutable:
aTuple = (1 , '2' , 3)
aList  = [1 , '2' , 3]
%whos


Variable   Type     Data/Info
-----------------------------
aList      list     n=3
aTuple     tuple    n=3


In [13]:
D = dict()
D

{}

In [15]:
D['Name'] = 'Abhimanyu'
D['Age'] = [20 , 30]
print(D)

{'Name': 'Abhimanyu', 'Age': [20, 30]}


In [22]:
D.items()
'name' not in D

True

###Dictionaries

In [25]:
%reset -f

D = dict()
num1 = float(input('Enter First Number:  '))
num2 = float(input('Enter Second Number: '))

D['firstNum'] = num1
D['secondNum'] = num2
D['prod'] = D['firstNum'] * D['secondNum']

print(D)
%whos

Enter First Number:  12
Enter Second Number: 3
{'firstNum': 12.0, 'secondNum': 3.0, 'prod': 36.0}
Variable   Type     Data/Info
-----------------------------
D          dict     n=3
num1       float    12.0
num2       float    3.0


In [43]:
aRange = range(12 , 13)
aRange

range(12, 13)

In [44]:
aList = list(aRange)
aList.append([1.2 , 1.3 , .4])
aList.append([2 , 3])
aList

[12, [1.2, 1.3, 0.4], [2, 3]]

In [48]:
aList[2][1]

3

### Slicing

In [50]:
aList = list(range(5,11))
aList

[5, 6, 7, 8, 9, 10]

In [55]:
aList[-3:]

[8, 9, 10]

###Functions:

In [59]:
# Functions
%reset -f

aList = list(range(10 , 50 , 10))
print(aList)

[10, 20, 30, 40]


In [66]:
print('sum = ' , sum(aList) )
print('Length = ' , len(aList) )
avg = sum(aList) / len(aList)
print('Mean = ' , avg)

sum =  100
Length =  4
Mean =  25.0


### Numpy Module:

In [76]:
%reset -f
%whos 

Interactive namespace is empty.


In [77]:
# import numpy as np
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/us<...>kages/numpy/__init__.py'>


In [79]:
aList = list(range(10 , 50 , 10))
print(aList)

[10, 20, 30, 40]


In [81]:
print('mean = ' , np.mean(aList) )  ; 

mean =  25.0


In [90]:
nparray = np.linspace(1 , 80 , 20)

In [89]:
%whos

Variable   Type       Data/Info
-------------------------------
aList      list       n=4
np         module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
nparray    ndarray    20: 20 elems, type `float64`, 160 bytes


In [97]:
nparray.sum()

810.0

###Pandas Module

In [99]:
%reset -f
import numpy as np
import pandas as pd
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
pd         module    <module 'pandas' from '/u<...>ages/pandas/__init__.py'>


In [105]:
# Create some random data:
var1 = 20 + 5 * np.random.randn(100)
print(var1)
print('Mean = ' , var1.mean() ) ; 
print('Std. Deviation = ' , var1.std() )

[22.56849509 18.31533027 15.70911367 16.70215793 20.53483649 24.14266836
 25.66428984 20.41649419 26.60680946 31.20948351 16.90359426 21.98425467
 30.42761018 24.88433723 19.01952833 22.54658934 10.75643814 20.8135213
 17.09806216 21.09123029 20.09959768 19.73728219 16.9347384  26.54797829
 17.95333288 16.75755175 28.88268469 19.00474701 11.61641577 13.65832353
 11.98183553 28.58658171 16.14613884 16.83037134 17.61188861 14.31837849
 24.40803932 22.53657689 23.64276724 15.84502872 24.18897367 14.91462152
 24.79305898 27.76557736 17.7148632  18.09614011 16.24124143 16.39185111
 27.28208574 26.74547508 20.3270964  17.62110007 19.26811625 14.02999315
 19.19869486 21.64819246 11.07087069 21.21076008 17.47829925 21.93560526
 14.12254992 17.55993218 17.64662528 26.7169943  20.98796843 17.72351607
 23.67130793 15.81090845 18.12351784 25.51028223 20.51560947 21.48505349
 18.04066055 17.25291681 23.31820572 14.83780614 22.65511386 21.02011964
 22.33914853 17.00740332 17.90097409 25.6211736  25.

In [107]:
var2 = np.random.randn(100) > 0
print(var2)

[False False False  True  True False  True False  True False  True False
 False  True  True  True False False False False False False False False
 False  True False False False False False  True  True  True False  True
  True  True False  True  True  True  True False False False False False
 False False  True False  True  True False False  True  True False  True
 False False False  True  True  True  True  True False False False False
  True  True False  True False False  True  True False False False  True
  True  True False False  True False  True False False  True  True False
  True False False False]


In [110]:
labels = ['Temp (C)' , 'Ice Creame Eaten']
print(labels)

['Temp (C)', 'Ice Creame Eaten']


In [112]:
# Now create a dictionary that contains this dataset:
D = {labels[0]:var1 , labels[1]:var2}
print(D)

{'Temp (C)': array([22.56849509, 18.31533027, 15.70911367, 16.70215793, 20.53483649,
       24.14266836, 25.66428984, 20.41649419, 26.60680946, 31.20948351,
       16.90359426, 21.98425467, 30.42761018, 24.88433723, 19.01952833,
       22.54658934, 10.75643814, 20.8135213 , 17.09806216, 21.09123029,
       20.09959768, 19.73728219, 16.9347384 , 26.54797829, 17.95333288,
       16.75755175, 28.88268469, 19.00474701, 11.61641577, 13.65832353,
       11.98183553, 28.58658171, 16.14613884, 16.83037134, 17.61188861,
       14.31837849, 24.40803932, 22.53657689, 23.64276724, 15.84502872,
       24.18897367, 14.91462152, 24.79305898, 27.76557736, 17.7148632 ,
       18.09614011, 16.24124143, 16.39185111, 27.28208574, 26.74547508,
       20.3270964 , 17.62110007, 19.26811625, 14.02999315, 19.19869486,
       21.64819246, 11.07087069, 21.21076008, 17.47829925, 21.93560526,
       14.12254992, 17.55993218, 17.64662528, 26.7169943 , 20.98796843,
       17.72351607, 23.67130793, 15.81090845, 18.12

In [115]:
# Now let's import the dictionary into a pandas dataframe: 
df = pd.DataFrame(data = D)
print(df)

     Temp (C)  Ice Creame Eaten
0   22.568495             False
1   18.315330             False
2   15.709114             False
3   16.702158              True
4   20.534836              True
..        ...               ...
95  23.981820             False
96  23.085488              True
97  24.622164             False
98  18.376150             False
99  16.597084             False

[100 rows x 2 columns]


In [117]:
df.head()

Temp (C)  Ice Creame Eaten
0  22.568495             False
1  18.315330             False
2  15.709114             False
3  16.702158              True
4  20.534836              True

In [118]:
df.count()

Temp (C)            100
Ice Creame Eaten    100
dtype: int64

In [119]:
df.mean()

Temp (C)            20.202421
Ice Creame Eaten     0.430000
dtype: float64

In [122]:
var1 = np.array(list(range(0 , 10)))
var1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
var2 = np.square(var1)
var2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [130]:
var3 = np.log(var2)
var3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 1.38629436, 2.19722458, 2.77258872,
       3.21887582, 3.58351894, 3.8918203 , 4.15888308, 4.39444915])

In [131]:
D = {'var1' : var1 , 'var2':var2 , 'var3':var3}
D

{'var1': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'var2': array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]),
 'var3': array([      -inf, 0.        , 1.38629436, 2.19722458, 2.77258872,
        3.21887582, 3.58351894, 3.8918203 , 4.15888308, 4.39444915])}

In [135]:
df = pd.DataFrame(data = D)
print(df)
df.head()

   var1  var2      var3
0     0     0      -inf
1     1     1  0.000000
2     2     4  1.386294
3     3     9  2.197225
4     4    16  2.772589
5     5    25  3.218876
6     6    36  3.583519
7     7    49  3.891820
8     8    64  4.158883
9     9    81  4.394449


var1  var2      var3
0     0     0      -inf
1     1     1  0.000000
2     2     4  1.386294
3     3     9  2.197225
4     4    16  2.772589