<a href="https://colab.research.google.com/github/dabhimanyu/learn_to_code/blob/python_codes/002_Mike_Python_lec_002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Flow Control STatments in Python:

In [ ]:
# if-else

%reset -f
import numpy as np
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/us<...>kages/numpy/__init__.py'>


In [ ]:
isinstance??
pj = np.arange(1 , 6)
tj = np.arange(6 , 1 , -1)
print(type(pj))
print('pj = ' + str(pj))
print('tj = ' + str(tj))
# pj = np.alist(np.arange(10))
isinstance(pj , np.ndarray)
print('Size of pj = ' + str(np.size(pj)) )
print('Product of Pj and Tj = ' + str(pj*tj) )

<class 'numpy.ndarray'>
pj = [1 2 3 4 5]
tj = [6 5 4 3 2]
Size of pj = 5
Product of Pj and Tj = [ 6 10 12 12 10]


In [ ]:
# Create a function to compute dot product:
# 1. check if both inputs are numpy arrays ( Hint: isinstance() )
# 2. Check if both arrays have same length
# 3. Return a meaningful error message
# 4. Compute dot product if things are in order:

def myDotProduct(arr1 , arr2):
  if not ( isinstance(arr1 , np.ndarray) and isinstance(arr2 , np.ndarray) ):
    raise Exception('Both Input variables needs to be numpy array')

  if not ( np.size(arr1) == np.size(arr2) ):
    raise Exception('Both Vectors should have same length')

  return( np.sum( arr1 * arr2) )

%whos

Variable       Type        Data/Info
------------------------------------
myDotProduct   function    <function myDotProduct at 0x7f0c94a62320>
np             module      <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
pj             ndarray     5: 5 elems, type `int64`, 40 bytes
tj             ndarray     5: 5 elems, type `int64`, 40 bytes


In [ ]:
myDotProduct(tj , pj)

50

### For Loop

In [ ]:
for i in range(1,6):
  print('Value Of i = ' + str(i))

Value Of i = 1
Value Of i = 2
Value Of i = 3
Value Of i = 4
Value Of i = 5


In [9]:
# Make a poisson like counter using loops:

# Parameter Lambda = 10
# Start at 1, multiply by random number uniform( [0 , 1] )
# Stop when target is less than exp(-lambda)
# count the number of iterations used to reach the target: exp(-lambda)

%reset -f
import numpy as np
np.random.uniform(0 , 1)
np.exp(-10)

4.5399929762484854e-05

###While Loop

In [21]:
toggle  =   True
target  =   1 ; 
count   =   0 ; 

# First way:
while toggle:
  target *=  target * np.random.uniform(0 , 1)
  count += 1 ; 
  print(str(count) + '. Target = ' + str(target)) ; 
  if target < np.exp(-10):
    break ; 

print('Counter = ' + str(count)) ; 

# Second way:
toggle  =   True
target  =   1 ; 
count   =   0 ; 

while toggle:
  target *=  target * np.random.uniform(0 , 1)
  count += 1 ; 
  print(str(count) + '. Target = ' + str(target)) ; 
  if target < np.exp(-10):
    toggle = False ; 

print('Counter = ' + str(count)) ; 

1. Target = 0.5765622561920287
2. Target = 0.2907575413319824
3. Target = 0.07476333136863557
4. Target = 0.0035358067796203278
5. Target = 4.691026136096293e-06
Counter = 5
1. Target = 0.9935952024771663
2. Target = 0.26012606217454526
3. Target = 0.0019958968674058863
4. Target = 9.346130381963803e-07
Counter = 4


###One line version of Loops and If-Else Statments:

In [24]:
# LIST Comphrension 

n = [i**2 - 2*i**0.5 for i in range(10) ]
n

[0.0,
 -1.0,
 1.1715728752538097,
 5.535898384862246,
 12.0,
 20.52786404500042,
 31.101020514433642,
 43.70849737787082,
 58.34314575050762,
 75.0]

In [27]:
# Short way of doing things:
# Notice the difference b/t the two:

n = [i**2 - 2*i**0.5 for i in range(10) if i > 4]
n

[20.52786404500042,
 31.101020514433642,
 43.70849737787082,
 58.34314575050762,
 75.0]

In [38]:
# Exercise:
i = 0
text = ['Abhimanyu' , 'has' , 'trouble' , 'in' , 'deciding' , 'left' , 'or' , 'right' , 'while' , 'driving' ] ; 

print(len(text))

[print(text[i]) for i in range(len(text))] ; 

10
Abhimanyu
has
trouble
in
deciding
left
or
right
while
driving


In [46]:
newList = ['']*10 ; 

newList = [ 'Odd' if i%2 == 1 else i for i in range(len(newList)) ] ; 
print(newList)

[0, 'Odd', 2, 'Odd', 4, 'Odd', 6, 'Odd', 8, 'Odd']


###Broadcasting In Numpy

In [104]:
%reset -f
import numpy as np
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/us<...>kages/numpy/__init__.py'>


In [82]:
X = np.array([ [1 , 2 , 3] , 
              [2 , 3 , 4] , 
              [3 , 4 , 5] , 
              [4 , 5 , 5] ])
print('X = '+ str(X) )
print('')
w = np.array([10 , 20 , 30])
print('w = ' + str(w) )

X = [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 5]]

w = [10 20 30]


In [83]:
np.shape(X)
X.shape

(4, 3)

In [84]:
Y = X
Y = X + w
Y

array([[11, 22, 33],
       [12, 23, 34],
       [13, 24, 35],
       [14, 25, 35]])

In [85]:
X

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 5]])

In [97]:
v = np.arange(9)
M = np.reshape(v , (3 , 3))
C = np.tile(M , (3 , 1))
print('C = ' + str(C)) ; print('')
print('v = ' + str(v) )

C = [[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]

v = [0 1 2 3 4 5 6 7 8]


In [102]:
print(np.reshape(v , (9 , 1)))
B = C * np.reshape(v , (len(v) , 1) )
B

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [ 0,  3,  6],
       [12, 16, 20],
       [30, 35, 40],
       [ 0,  6, 12],
       [21, 28, 35],
       [48, 56, 64]])

###Formatting Print Statments:

In [143]:
# a is the 1st letter of the alphabet.
# .
# .
# .
# z is the 26th letter of the alphabet

import string

z = np.array( list(string.ascii_lowercase ) )
type(z)
print(z.size)
i = 0 ; 
print('%s is the %2ist letter of the alphabet.' %( z[0] , i+1)) ; i = 1
print('%s is the %2ind letter of the alphabet.' %( z[1] , i+1)) ; i = 2
print('%s is the %2ird letter of the alphabet.' %( z[2] , i+1)) ; 

for i in range(3 , z.size):
  print('%s is the %2ith letter of the alphabet.' %( z[0] , i+1)) ;

26
a is the  1st letter of the alphabet.
b is the  2nd letter of the alphabet.
c is the  3rd letter of the alphabet.
a is the  4th letter of the alphabet.
a is the  5th letter of the alphabet.
a is the  6th letter of the alphabet.
a is the  7th letter of the alphabet.
a is the  8th letter of the alphabet.
a is the  9th letter of the alphabet.
a is the 10th letter of the alphabet.
a is the 11th letter of the alphabet.
a is the 12th letter of the alphabet.
a is the 13th letter of the alphabet.
a is the 14th letter of the alphabet.
a is the 15th letter of the alphabet.
a is the 16th letter of the alphabet.
a is the 17th letter of the alphabet.
a is the 18th letter of the alphabet.
a is the 19th letter of the alphabet.
a is the 20th letter of the alphabet.
a is the 21th letter of the alphabet.
a is the 22th letter of the alphabet.
a is the 23th letter of the alphabet.
a is the 24th letter of the alphabet.
a is the 25th letter of the alphabet.
a is the 26th letter of the alphabet.
